export enum EventType {
  MULTIPLE_QUIZ = "MULTIPLE_QUIZ",
  SHORT_QUIZ = "SHORT_QUIZ",
  ESSAY_QUIZ = "ESSAY_QUIZ",
  QUIZ_RESULT = "QUIZ_RESULT",
  FIRST_HINT = "FIRST_HINT",
  SECOND_HINT = "SECOND_HINT",
  ONE_ATTACK = "ONE_ATTACK",
  TWO_ATTACK = "TWO_ATTACK",
  REWARD = "REWARD",
}
