--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.account (
    account_type integer NOT NULL,
    account_balance bigint NOT NULL,
    account_id bigint NOT NULL,
    member_id bigint NOT NULL,
    account_name character varying(255) NOT NULL,
    account_no character varying(255) NOT NULL,
    bank_code character varying(255) NOT NULL
);


ALTER TABLE public.account OWNER TO root;

--
-- Name: account_account_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.account ALTER COLUMN account_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_multiple_choice_quiz; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.ai_multiple_choice_quiz (
    ai_quiz_id bigint NOT NULL,
    multiple_choice_quiz_id bigint NOT NULL,
    ai_multiple_question character varying(255) NOT NULL
);


ALTER TABLE public.ai_multiple_choice_quiz OWNER TO root;

--
-- Name: ai_multiple_choice_quiz_multiple_choice_quiz_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.ai_multiple_choice_quiz ALTER COLUMN multiple_choice_quiz_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_multiple_choice_quiz_multiple_choice_quiz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_option; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.ai_option (
    is_correct boolean NOT NULL,
    ai_option_id bigint NOT NULL,
    multiple_choice_quiz_id bigint NOT NULL,
    ai_option_text character varying(255) NOT NULL
);


ALTER TABLE public.ai_option OWNER TO root;

--
-- Name: ai_option_ai_option_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.ai_option ALTER COLUMN ai_option_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_option_ai_option_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_quiz; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.ai_quiz (
    is_deleted boolean NOT NULL,
    ai_quiz_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    member_id bigint NOT NULL
);


ALTER TABLE public.ai_quiz OWNER TO root;

--
-- Name: ai_quiz_ai_quiz_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.ai_quiz ALTER COLUMN ai_quiz_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_quiz_ai_quiz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_quiz_log; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.ai_quiz_log (
    is_correct boolean NOT NULL,
    ai_quiz_id bigint NOT NULL,
    ai_quiz_log_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    member_id bigint NOT NULL,
    user_answer character varying(255)
);


ALTER TABLE public.ai_quiz_log OWNER TO root;

--
-- Name: ai_quiz_log_ai_quiz_log_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.ai_quiz_log ALTER COLUMN ai_quiz_log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_quiz_log_ai_quiz_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_spend_category; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.ai_spend_category (
    id bigint NOT NULL,
    category character varying(255),
    keyword character varying(255),
    CONSTRAINT ai_spend_category_category_check CHECK (((category)::text = ANY ((ARRAY['FOOD'::character varying, 'TRANSPORT'::character varying, 'HOUSING'::character varying, 'MEDICAL'::character varying, 'CULTURE'::character varying, 'SHOPPING'::character varying, 'EDUCATION'::character varying, 'ETC'::character varying])::text[])))
);


ALTER TABLE public.ai_spend_category OWNER TO root;

--
-- Name: ai_spend_category_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.ai_spend_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_spend_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cat; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.cat (
    cat_id bigint NOT NULL,
    cat_name character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    grade character varying(255),
    CONSTRAINT cat_grade_check CHECK (((grade)::text = ANY ((ARRAY['DEFAULT'::character varying, 'COMMON'::character varying, 'EPIC'::character varying, 'LEGENDARY'::character varying])::text[])))
);


ALTER TABLE public.cat OWNER TO root;

--
-- Name: cat_cat_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.cat ALTER COLUMN cat_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cat_cat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_log; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.chat_log (
    id bigint NOT NULL,
    sender bigint,
    content character varying(255),
    room_id character varying(255)
);


ALTER TABLE public.chat_log OWNER TO root;

--
-- Name: chat_log_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.chat_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: essay_quiz; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.essay_quiz (
    quiz_id bigint NOT NULL,
    essay_first_hint character varying(255) NOT NULL,
    essay_question character varying(255) NOT NULL,
    essay_second_hint character varying(255) NOT NULL
);


ALTER TABLE public.essay_quiz OWNER TO root;

--
-- Name: finance_member; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.finance_member (
    created_at timestamp(6) without time zone NOT NULL,
    member_id bigint NOT NULL,
    finance_key character varying(255) NOT NULL,
    main_account character varying(255)
);


ALTER TABLE public.finance_member OWNER TO root;

--
-- Name: game_room; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.game_room (
    score integer NOT NULL,
    id bigint NOT NULL,
    room_id character varying(255),
    status character varying(255)
);


ALTER TABLE public.game_room OWNER TO root;

--
-- Name: game_room_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.game_room ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.game_room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: member; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.member (
    created_at timestamp(6) without time zone NOT NULL,
    exp bigint NOT NULL,
    last_login timestamp(6) without time zone,
    member_id bigint NOT NULL,
    point bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    email character varying(255),
    main_cat character varying(255),
    nickname character varying(255) NOT NULL,
    provider_id character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT member_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


ALTER TABLE public.member OWNER TO root;

--
-- Name: member_cat; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.member_cat (
    cat_id bigint,
    member_cat_id bigint NOT NULL,
    member_id bigint
);


ALTER TABLE public.member_cat OWNER TO root;

--
-- Name: member_cat_member_cat_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.member_cat ALTER COLUMN member_cat_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_cat_member_cat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: member_member_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.member ALTER COLUMN member_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: multiple_choice_quiz; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.multiple_choice_quiz (
    quiz_id bigint NOT NULL,
    multiple_first_hint character varying(255) NOT NULL,
    multiple_question character varying(255) NOT NULL,
    multiple_second_hint character varying(255) NOT NULL
);


ALTER TABLE public.multiple_choice_quiz OWNER TO root;

--
-- Name: quiz; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.quiz (
    quiz_id bigint NOT NULL,
    created_at character varying(255) NOT NULL,
    quiz_mode character varying(255) NOT NULL,
    subject_type character varying(255) NOT NULL,
    CONSTRAINT quiz_quiz_mode_check CHECK (((quiz_mode)::text = ANY ((ARRAY['SHORT_ANSWER'::character varying, 'ESSAY'::character varying, 'MULTIPLE_CHOICE'::character varying])::text[]))),
    CONSTRAINT quiz_subject_type_check CHECK (((subject_type)::text = ANY ((ARRAY['FIN_KNOWLEDGE'::character varying, 'FIN_CRIME'::character varying, 'FIN_POLICY'::character varying, 'FIN_PRODUCT'::character varying, 'FIN_INVESTMENT'::character varying])::text[])))
);


ALTER TABLE public.quiz OWNER TO root;

--
-- Name: quiz_log; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.quiz_log (
    is_correct boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    member_id bigint NOT NULL,
    quiz_id bigint NOT NULL,
    quiz_log_id bigint NOT NULL,
    user_answer character varying(255)
);


ALTER TABLE public.quiz_log OWNER TO root;

--
-- Name: quiz_log_quiz_log_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.quiz_log ALTER COLUMN quiz_log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_log_quiz_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quiz_option; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.quiz_option (
    is_correct boolean,
    quiz_id bigint,
    quiz_option_id bigint NOT NULL,
    option_text character varying(255)
);


ALTER TABLE public.quiz_option OWNER TO root;

--
-- Name: quiz_option_quiz_option_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.quiz_option ALTER COLUMN quiz_option_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_option_quiz_option_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quiz_quiz_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.quiz ALTER COLUMN quiz_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_quiz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: room; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.room (
    max_player integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    member_id bigint,
    room_id bigint NOT NULL,
    password character varying(255),
    room_title character varying(255) NOT NULL,
    room_type character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    subject_type character varying(255) NOT NULL,
    update_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT room_room_type_check CHECK (((room_type)::text = ANY ((ARRAY['ONE_ON_ONE'::character varying, 'MULTI'::character varying, 'AI_BATTLE'::character varying])::text[]))),
    CONSTRAINT room_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'IN_PROGRESS'::character varying, 'CLOSED'::character varying])::text[]))),
    CONSTRAINT room_subject_type_check CHECK (((subject_type)::text = ANY ((ARRAY['FIN_KNOWLEDGE'::character varying, 'FIN_CRIME'::character varying, 'FIN_POLICY'::character varying, 'FIN_PRODUCT'::character varying, 'FIN_INVESTMENT'::character varying])::text[])))
);


ALTER TABLE public.room OWNER TO root;

--
-- Name: room_room_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.room ALTER COLUMN room_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.room_room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: short_answer_quiz; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.short_answer_quiz (
    quiz_id bigint NOT NULL,
    short_answer character varying(255) NOT NULL,
    short_first_hint character varying(255),
    short_question character varying(255) NOT NULL,
    short_second_hint character varying(255)
);


ALTER TABLE public.short_answer_quiz OWNER TO root;

--
-- Name: spend_category; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.spend_category (
    id bigint NOT NULL,
    category character varying(255),
    keyword character varying(255),
    CONSTRAINT spend_category_category_check CHECK (((category)::text = ANY ((ARRAY['FOOD'::character varying, 'TRANSPORT'::character varying, 'HOUSING'::character varying, 'MEDICAL'::character varying, 'CULTURE'::character varying, 'SHOPPING'::character varying, 'EDUCATION'::character varying, 'ETC'::character varying])::text[])))
);


ALTER TABLE public.spend_category OWNER TO root;

--
-- Name: spend_category_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.spend_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spend_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: account; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.account (account_type, account_balance, account_id, member_id, account_name, account_no, bank_code) FROM stdin;
1	0	1	1	증권	0816151787058593	081
1	0	2	1	수시입출금	0901194847289460	090
1	0	3	1	가상화폐	9998882391091738	999
1	0	7	4	가상화폐	0042295554542425	004
1	0	8	4	증권	0813561438764553	081
1	0	10	4	수시입출금 계좌	9996186568511042	999
1	914200	9	4	수시입출금	0902945924047090	090
1	0	15	15	증권	0815385351700911	081
1	0	16	15	수시입출금 계좌	0903187459151182	090
1	498800000	17	15	가상화폐	9993867338281332	999
1	1624000	18	3	증권	0812736327748134	081
1	1929800	19	3	수시입출금	0900115488250715	090
1	497000	20	3	가상화폐	9992060042788631	999
1	472000	11	5	수시입출금	0909037558728923	090
\.


--
-- Data for Name: cat; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.cat (cat_id, cat_name, description, grade) FROM stdin;
1	batman	밤을 지키는 히어로냥이에요.	EPIC
2	christmas	연말 분위기 물씬 나는 축제냥이에요.	EPIC
3	classic	전통미 넘치는 기본 고양이에요.	DEFAULT
4	demonic	장난꾸러기 마성의 고양이에요.	EPIC
5	egypt	고대 느낌의 신비한 고양이에요.	COMMON
6	simase	도도한 매력의 샴 고양이에요.	COMMON
7	tiger	작은 호랑이 같은 전설냥이에요.	LEGENDARY
8	unique_rabbit	토끼 닮은 미스터리한 고양이에요.	LEGENDARY
9	master	명령하는 눈빛의 마스터냥이에요.	COMMON
10	slave	사랑 많은 순둥이 고양이에요.	COMMON
\.


--
-- Data for Name: essay_quiz; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.essay_quiz (quiz_id, essay_first_hint, essay_question, essay_second_hint) FROM stdin;
60	예금자 보호 장치에 대해 비판적 시각으로 접근해보세요.	 예금 보험 제도의 한계와 개선 방안에 대해 논하시오.	한도 초과, 구조적 한계 등 개선점을 중심으로 논의하세요.
51	경제의 흐름을 바꾸는 정부의 여러 정책 중 하나입니다.	 통화 정책이 경제에 미치는 장단점에 대하여 자세히 설명하시오.	금리 조절이나 화폐 공급량 변화가 대표적인 수단입니다.
52	금리가 경제에 미치는 영향은 복합적입니다.	 예금 금리가 지속적으로 하락한다면 개인 가계와 기업에 어떤 영향이 있을지 논하시오.	이자 수익의 감소는 저축과 소비에 영향을 줄 수 있습니다.
53	가격 변동에 따른 경제적 현상 두 가지를 비교해보세요.	 인플레이션과 디플레이션의 차이, 그리고 각각이 경제에 미치는 영향을 서술하시오.	물가의 지속적인 상승 또는 하락이 주요 개념입니다.
54	금융 시스템에서 중심이 되는 기관의 역할을 떠올려보세요.	 금융 시스템에서 중앙은행의 역할과 필요성에 대해 구체적으로 설명하시오.	금리 결정, 통화 발행 등을 담당합니다.
55	금융시장 개방이 경제에 미치는 영향을 논해보세요.	 금융 자유화가 경제 발전에 미치는 영향과 부작용에 대하여 논하시오.	자본 이동이 자유로워짐에 따른 장점과 단점이 존재합니다.
56	금리 상황에 따른 개인 자산 전략을 생각해보세요.	 금리 인상기와 금리 인하기에 각각 적절한 개인 금융 전략을 제시하시오.	고정금리·변동금리 선택이나 저축과 대출 전략이 포함됩니다.
57	금융기관이 무너지면 어떤 일이 생길까요?	 금융기관 파산이 경제 전반에 끼치는 여파와 이를 방지하기 위한 제도적 장치들을 설명하시오.	예금자 보호나 금융시장 혼란을 막기 위한 제도가 필요합니다.
58	개인 금융 역량이 사회 전반에 미치는 영향을 생각해보세요.	 소비자 금융 이해력 향상을 위한 교육의 중요성과 방안을 구체적으로 제시하시오.	기초적인 금융 지식 교육이 중요한 요소입니다.
59	기술의 발전이 전통 금융업에 끼친 영향을 생각해보세요.	 핀테크(FinTech)의 등장으로 인한 전통 금융기관의 변화와 미래 전망을 서술하시오.	디지털 기술의 접목으로 인한 서비스 변화가 중심입니다.
61	급격한 자산 가격 상승은 다양한 원인이 있습니다.	 주식 시장 거품(Bubble) 현상의 원인과 대응 방안에 대해 논하시오.	과도한 기대심리와 유동성 증가가 영향을 줄 수 있습니다.
62	개인 투자자들이 종종 반복하는 실수가 존재합니다.	 개인 투자자들이 흔히 범하는 오류와 이를 예방하는 전략을 제시하시오.	충동적 투자나 정보 부족이 대표적인 사례입니다.
63	위험 회피 및 헤지 수단이 되는 파생상품입니다.	 파생상품(옵션, 선물) 시장의 역할과 위험성에 대해 서술하시오.	옵션과 선물은 높은 수익과 리스크를 동시에 가집니다.
64	투자 전략에는 다양한 접근 방식이 있습니다.	 가치투자와 모멘텀투자의 차이점과 장단점에 대해 비교하시오.	하나는 내재 가치를 보고, 다른 하나는 추세를 따릅니다.
65	주주의 권리와 기업 경영은 밀접하게 연결됩니다.	 주주행동주의(Activist Shareholder)가 회사 경영에 미치는 영향과 사례를 설명하시오.	경영 개선을 요구하는 활동이 영향을 줄 수 있습니다.
66	지속가능성과 사회 책임이 중요한 요소로 부상 중입니다.	 ESG(환경·사회·지배구조) 투자 트렌드가 기업 가치 평가에 미치는 영향을 논하시오.	환경·사회·지배구조 기준이 투자 판단에 영향을 미칩니다.
67	금리는 다양한 시장에 영향을 미칩니다.	 채권금리 변동이 주식 시장과 기업 자금 조달에 미치는 영향을 분석하시오.	채권금리 변동은 기업 자금 조달비용을 바꿀 수 있습니다.
68	해외 투자 시 위험 요소 중 하나는 환율입니다.	 해외 주식 투자 시 고려해야 할 환율 리스크와 대응 방법을 서술하시오.	환율 변동에 따른 손실을 줄이기 위한 방법이 필요합니다.
69	헤지펀드는 고위험 고수익 전략을 사용합니다.	 헤지펀드(Hedge Fund)의 투자 전략과 레버리지 활용에 대해 논하시오.	레버리지를 활용한 전략은 큰 손실도 유발할 수 있습니다.
70	IPO는 기업 성장의 전환점이 될 수 있습니다.	 IPO(기업공개)가 기업과 투자자 모두에게 가지는 의미와 이슈를 서술하시오.	공개 과정에서 발생하는 이해관계 조정이 필요합니다.
71	재정 운영에는 두 가지 대표적인 방향이 있습니다.	 확장적 재정정책과 긴축적 재정정책의 장단점을 비교하시오.	지출을 늘리는 확장적 정책과 줄이는 긴축 정책이 있습니다.
72	인구 구조 변화는 정책 변화로 이어집니다.	 저출산·고령화 문제를 해결하기 위한 재정 및 복지 정책 방안에 대해 논하시오.	복지 지출 확대와 노동시장 개혁 등이 주요 대응입니다.
73	임금 정책은 노동시장에 직접적 영향을 줍니다.	 최저임금 인상이 시장에 미치는 효과와 그 한계에 대해 서술하시오.	최저임금 인상은 고용 및 비용에 영향을 미칠 수 있습니다.
74	공공서비스의 민간 이전은 장단점이 있습니다.	 공공부문의 역할과 민영화 정책의 필요성 및 부작용에 대해 논하시오.	효율성은 높아질 수 있으나 형평성 문제도 생깁니다.
75	세금 정책은 자산 보유에 영향을 미칠 수 있습니다.	 부동산 보유세 강화 정책의 경제적·사회적 영향에 대해 서술하시오.	보유세 강화는 시장 안정에 긍정적 영향을 줄 수 있습니다.
76	정책 수립 시 소외계층을 고려해야 합니다.	 복지 사각지대를 줄이기 위한 정부의 정책 수립 시 고려 사항을 제시하시오.	복지 시스템 사각지대를 줄이기 위한 기준 설정이 필요합니다.
77	경제 양극화는 산업 구조와도 연결됩니다.	 대기업과 중소기업 간의 양극화를 완화하기 위한 정부 지원 정책 방안을 논하시오.	중소기업에 대한 지원 정책은 균형 발전에 중요합니다.
78	지역 간 불균형 해소는 큰 정책 과제입니다.	 지역 균형 발전을 위한 재정 분권화 정책의 필요성과 과제를 서술하시오.	재정 자율성과 자원 배분 구조 개선이 핵심입니다.
79	의료 정책은 재정과 서비스 모두에 영향을 줍니다.	 공공의료 확대와 건강보험 재정 안정화 정책 간의 균형점을 논하시오.	지속가능성과 보장성을 균형 있게 맞추는 것이 중요합니다.
80	녹색 성장은 미래의 중요한 과제입니다.	 탄소중립 목표 달성을 위한 녹색 금융·투자 확대 정책의 방향성을 제시하시오.	친환경 산업에 대한 금융 지원과 규제가 함께 이루어져야 합니다.
81	보험은 위험 관리 도구로 활용됩니다.	 보험 가입 시 고려해야 할 주요 요소와 잘못된 가입 사례에 대해 논하시오.	보장 범위, 납입 기간 등 조건을 고려해야 합니다.
82	노후 대비 상품에는 여러 형태가 있습니다.	 은퇴 대비 연금상품 선택 시 유의해야 할 사항과 비교 기준을 서술하시오.	연금 수령 시기, 수익률, 세제 혜택 등이 중요 요소입니다.
83	변액보험은 투자 성과에 따라 수익이 달라집니다.	 변액보험의 특징과 위험성을 구체적으로 설명하시오.	원금 보장이 없고 수익 변동성이 클 수 있습니다.
84	디지털 금융은 편리성과 동시에 위험도 내포합니다.	 디지털 금융상품(모바일 뱅킹, 로보어드바이저 등)의 장점과 리스크를 논하시오.	보안, 접근성, 기술 의존성 등이 고려되어야 합니다.
85	금리 인하 시 대체 수단이 필요합니다.	 예·적금 금리 하락 시기에 투자 대안 상품을 찾는 방법을 서술하시오.	위험과 수익의 균형이 잡힌 상품 선택이 중요합니다.
86	소비자 보호는 금융 상품 이해에서 시작됩니다.	 금융상품 가입 전 상품설명서 확인의 중요성과 소비자 보호 제도를 논하시오.	설명서의 내용을 충분히 숙지하는 것이 필수입니다.
87	ETF와 펀드는 구조와 유동성에 차이가 있습니다.	 ETF와 펀드 상품의 차이점과 각각의 장단점을 비교하시오.	ETF는 실시간 거래 가능, 펀드는 정산 방식이 다릅니다.
88	금융기관별 대출 상품 특성은 상이합니다.	 은행권 대출 상품과 제2금융권 대출 상품의 특징 및 금리 구조를 비교하시오.	금리, 심사 기준, 상환 방식 등이 달라집니다.
89	신용카드 서비스는 유용하지만 부채로 이어질 수 있습니다.	 신용카드 리볼빙 서비스의 장단점과 부채 관리 측면에서의 문제점을 논하시오.	리볼빙 서비스는 이자가 누적될 수 있으니 주의가 필요합니다.
90	디지털 전환이 금융 환경을 바꾸고 있습니다.	 인터넷 전문은행이 전통 은행 시장에 가져온 변화와 앞으로의 전망을 설명하시오.	인터넷 전문은행은 접근성과 편의성을 강조합니다.
91	사이버 사기의 수법은 계속 진화하고 있습니다.	 사이버 금융사기의 최신 기법과 이에 대응하기 위한 기술적·제도적 방안을 서술하시오.	기술적 방어와 제도적 장치가 동시에 작동해야 합니다.
92	다단계 사기는 정보 부족을 악용합니다.	 유사수신행위(불법 다단계) 피해 예방을 위한 금융교육 방안을 논하시오.	금융교육을 통해 위험 신호를 인지하는 것이 중요합니다.
93	내부자 거래는 시장의 공정성을 해칩니다.	 내부자 거래(Insider Trading)의 심각성과 이를 방지하기 위한 규제 방안에 대해 설명하시오.	엄격한 공시와 제재가 예방 수단이 될 수 있습니다.
94	자금세탁은 글로벌 범죄와 연결됩니다.	 자금세탁(돈세탁)의 대표적 수법과 국제 공조의 중요성에 대해 서술하시오.	국가 간 협력이 필수적인 대응 방법입니다.
95	가상자산은 규제 사각지대에 있었습니다.	 가상자산(암호화폐) 관련 사기 유형과 규제 현황, 그리고 개선책에 대해 논하시오.	투자자 보호와 기술 발전 사이 균형이 필요합니다.
96	결제 시스템은 보안이 가장 중요한 요소입니다.	 전자지급결제 시스템 보안 취약점과 금융기관이 취해야 할 보호조치를 논하시오.	이중 인증, 거래 제한 등 기술적 조치가 필요합니다.
97	보이스피싱은 조직적으로 운영됩니다.	 보이스피싱 조직의 구조와 돈세탁 경로 차단을 위한 수사기법에 대해 서술하시오.	자금 흐름을 추적하고 차단하는 수사 기술이 중요합니다.
98	인증 방식 변화로 다양한 대체 수단이 등장했습니다.	 공인인증서 폐지 이후 등장한 대체 인증수단들의 보안성과 편의성을 비교하시오.	생체 인증, 간편 인증의 장단점을 비교해보세요.
99	ICO는 고수익과 동시에 고위험을 내포합니다.	 ICO(Initial Coin Offering) 사기 사례를 통한 투자자 보호 방안에 대해 논하시오.	정보 제공과 사전 심사제도가 보호 수단이 될 수 있습니다.
100	AI는 금융사기에 새로운 기회를 제공합니다.	 AI 기술 발달로 인한 금융사기 유형 변화와 향후 규제 방향을 예상하시오.	위조 음성, 딥페이크 등 새로운 형태가 등장 중입니다.
\.


--
-- Data for Name: multiple_choice_quiz; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.multiple_choice_quiz (quiz_id, multiple_first_hint, multiple_question, multiple_second_hint) FROM stdin;
101	국가의 경제 기관 중 하나입니다.	 중앙은행의 주된 역할은 무엇일까요?	화폐와 통화량 조절에 중심 역할을 합니다.
102	이자에 대한 개념을 배울 때 등장합니다.	 복리 효과의 올바른 설명은 무엇인가요?	이전 이자도 함께 계산에 포함됩니다.
103	금융사 파산 시 중요한 제도입니다.	 예금보험제도의 보장 한도는 어떻게 되나요?	5천만 원까지 보호되는 금융 안전 장치입니다.
104	중앙은행의 정책 중 하나와 연관 있습니다.	 다음 중 지급준비율이 인상될 때 나타날 수 있는 효과는?	대출 규모가 줄어들 가능성이 있습니다.
105	금융거래 시 중요하지만 잘 드러나지 않는 요소입니다.	 신용등급이 높은 사람이 얻을 수 있는 이점은?	대출 조건에 유리하게 작용할 수 있습니다.
106	정부 기관 중 하나를 떠올릴 수 있습니다.	 적정 금리 정책을 결정하는 주요 기관은 어디인가요?	한국은행이 결정하는 정책과 관련 있습니다.
107	대출 조건에서 고려되는 보조적인 요소입니다.	 담보 대출 시 담보 물건의 가치가 중요한 이유는?	대출 회수 가능성에 영향을 줍니다.
108	금융감독원 외의 기관도 떠올릴 수 있습니다.	 금융감독원의 주 업무는 무엇인가요?	금융기관의 건전성을 유지하는 활동입니다.
109	금리가 내려가면 생길 수 있는 여러 현상 중 하나입니다.	 금리가 낮아질 경우 나타나는 일반적인 현상은?	소비자들의 지출이 증가할 수 있습니다.
110	세금과 관련된 경제 용어일 수도 있습니다.	 다음 중 통화정책 수단에 해당하지 않는 것은 무엇인가요?	통화 정책에 직접적인 수단이 아닙니다.
111	금융 기관 중 하나에서 개설합니다.	 주식을 사기 위해 계좌를 개설하는 곳은 어디인가요?	주식을 거래하기 위한 전용 계좌가 필요합니다.
112	일반 투자 상품과는 차이가 있습니다.	 채권에 대한 설명 중 옳은 것은 무엇인가요?	이자를 정기적으로 지급받을 수 있는 상품입니다.
113	리스크 관리 기법 중 하나입니다.	 분산투자의 가장 큰 목적은 무엇인가요?	여러 자산에 나누어 투자하는 전략입니다.
114	주가와 배당의 관계를 반영합니다.	 배당 수익률이 높다는 것은 어떤 의미일까요?	투자금 대비 배당 수익률을 나타냅니다.
115	펀드와 주식의 특성이 섞여 있습니다.	 ETF(상장지수펀드)에 대한 설명으로 옳은 것은?	지수를 추종하며 주식처럼 실시간 매매가 가능합니다.
116	기업 가치 판단에 쓰이는 지표입니다.	 PER(주가수익비율)이 높은 기업은 일반적으로 어떤 의미인가요?	수익 대비 주가가 얼마나 높은지를 나타냅니다.
117	하락장에서도 수익을 추구하는 전략입니다.	 공매도 전략의 주요 목적은 무엇일까요?	주식을 빌려서 매도한 후 되사는 방식입니다.
118	투자 전략을 세우는 데 쓰이는 분석 방식입니다.	 기술적 분석과 펀더멘털 분석의 차이는 무엇인가요?	하나는 차트를, 다른 하나는 기업의 재무 상태를 중시합니다.
119	장기적 관점의 투자 방식입니다.	 가치투자에서 가장 중요하게 보는 요소는 무엇인가요?	기업의 재무 상태와 내재 가치를 중시합니다.
120	주주가 적극적으로 의견을 표출하는 행동입니다.	 주주행동주의(Activist Shareholder)에 대한 설명으로 옳은 것은?	기업 경영진에게 전략적 변화를 요구할 수 있습니다.
121	경제 정책 중 하나입니다.	 재정정책에 대한 설명으로 옳은 것은 무엇인가요?	정부 지출과 세금 정책을 조절하는 방식입니다.
122	금리 조정과 관련이 있는 수단입니다.	 다음 중 통화정책의 수단으로 활용되는 것은 무엇인가요?	통화량을 조절하는 대표적인 방법입니다.
123	부동산과 관련된 정책입니다.	 부동산 정책의 주요 목적은 무엇일까요?	시장 과열을 억제하고 가격 안정을 목적으로 합니다.
124	소득 재분배 정책 중 하나입니다.	 기본소득의 특징으로 맞는 것은 무엇인가요?	국민 모두에게 조건 없이 지급되는 소득입니다.
125	세금 정책의 영향에 대해 생각해보세요.	 조세정책이 경제에 미치는 영향으로 옳은 것은?	소득 재분배와 경기 조절 수단으로 작용할 수 있습니다.
126	미래 세대와 연결될 수 있는 경제 문제입니다.	 정부 부채가 과도하게 증가했을 때 나타날 수 있는 문제는?	채무 부담이 커지고 재정 운용에 부담이 생길 수 있습니다.
127	복지 정책의 유형 비교입니다.	 복지 정책에서 보편 복지와 선별 복지의 차이는 무엇인가요?	하나는 전체 국민 대상, 다른 하나는 특정 계층 대상입니다.
128	경제 침체기와 연관 있는 정책입니다.	 확장적 재정정책이 필요한 상황은 언제인가요?	정부가 적극적으로 돈을 쓰는 시기에 활용됩니다.
129	국가가 제공하는 공적 서비스입니다.	 공공재의 예시에 해당하는 것은 무엇인가요?	치안, 국방, 도로 등 모두가 이용할 수 있는 자원입니다.
130	국가 재정을 안정적으로 유지하기 위한 수단입니다.	 재정건전성을 위해 필요한 조치는 무엇인가요?	채무를 줄이고 균형 재정을 유지하는 것이 핵심입니다.
131	두 가지 저축 방식의 비교입니다.	 적금과 예금의 차이로 옳은 것은 무엇인가요?	하나는 매월 납입, 다른 하나는 목돈을 한 번에 예치합니다.
132	재무 계획의 중요한 도구 중 하나입니다.	 보험 가입의 주된 목적은 무엇인가요?	예기치 못한 사고나 질병에 대비하는 수단입니다.
133	노후 대비 금융 상품입니다.	 연금저축의 특징으로 맞는 것은 무엇인가요?	세제 혜택을 제공하는 장기 투자 상품입니다.
134	간접 투자 수단입니다.	 펀드 상품에 대한 일반적인 설명으로 옳은 것은?	여러 자산에 투자하여 위험을 분산시킬 수 있습니다.
135	단기 자금 운용 계좌입니다.	 CMA 계좌의 장점으로 맞는 것은 무엇인가요?	수시 입출금이 가능하고 이자가 발생합니다.
136	개인 자산 통합 계좌입니다.	 ISA(개인종합자산관리계좌)에 대한 설명 중 옳은 것은?	여러 금융 상품을 하나의 계좌로 관리할 수 있습니다.
137	정기적으로 투자하는 방식입니다.	 적립식 펀드 투자 시 장점으로 맞는 것은?	정해진 금액을 나눠 투자해 평균 단가를 낮춥니다.
138	금리 구조에 대한 이해가 필요합니다.	 고정금리와 변동금리의 차이에 대한 옳은 설명은?	약정된 기간 동안 금리가 고정되거나 변동될 수 있습니다.
139	대출 가능 금액 결정의 핵심 요소입니다.	 대출 한도를 결정하는 주요 요인은 무엇인가요?	소득, 신용등급, 담보 등을 종합적으로 고려합니다.
140	은행과의 차이점을 중심으로 보세요.	 제2금융권 대출 상품의 특징으로 옳은 것은 무엇인가요?	대출이 쉬울 수 있지만 금리가 높을 수 있습니다.
141	전자금융 범죄 유형 중 하나입니다.	 보이스피싱의 특징으로 옳은 것은?	기관을 사칭하며 금전이나 정보를 요구합니다.
142	문자 기반 사기의 한 종류입니다.	 스미싱에 대한 올바른 설명은 무엇인가요?	링크 클릭 유도로 정보를 탈취합니다.
143	불법 금융의 대표적 사례입니다.	 불법 사금융 피해를 예방하려면 어떻게 해야 하나요?	고금리와 과도한 수수료를 부과하는 금융 행위입니다.
144	사이버 보안과 관련된 범죄입니다.	 사이버 금융사기 방지를 위해 개인이 취할 수 있는 조치는 무엇인가요?	계정 탈취나 해킹을 통한 금전 피해가 발생할 수 있습니다.
145	급한 상황을 조장하는 사기 수법입니다.	 계좌이체 사기가 의심되는 상황에서 가장 먼저 해야 할 일은 무엇인가요?	진위를 파악하지 못하게 한 뒤 이체를 유도합니다.
146	전자금융 관련 사기의 일반적 특징입니다.	 전자금융사기의 공통적인 특징은 무엇인가요?	정보를 탈취하거나 자금을 빼내는 방식입니다.
147	가짜 사이트를 구별하는 방법입니다.	 피싱 사이트를 구별하는 방법 중 맞는 것은?	주소와 보안 여부를 꼼꼼히 확인해야 합니다.
148	금융 사기 피해 발생 후 대응입니다.	 금융 범죄 피해를 입은 경우 취해야 할 조치는 무엇인가요?	즉시 계좌 정지를 요청하는 것이 중요합니다.
149	불법 투자 구조에 대한 설명입니다.	 다단계 금융사기의 구조적 특징으로 옳은 것은?	후속 투자자의 자금으로 앞선 투자자에게 지급됩니다.
150	온라인 결제 보안에 대한 문제입니다.	 전자지급결제 사기의 대표적 예방법으로 적절한 것은 무엇인가요?	출처를 확인하지 않은 앱 설치는 위험할 수 있습니다.
\.


--
-- Data for Name: quiz; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.quiz (quiz_id, created_at, quiz_mode, subject_type) FROM stdin;
1	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_KNOWLEDGE
2	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_KNOWLEDGE
3	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_KNOWLEDGE
4	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_KNOWLEDGE
5	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_KNOWLEDGE
6	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_KNOWLEDGE
7	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_KNOWLEDGE
8	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_KNOWLEDGE
9	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_KNOWLEDGE
10	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_KNOWLEDGE
11	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_INVESTMENT
12	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_INVESTMENT
13	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_INVESTMENT
14	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_INVESTMENT
15	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_INVESTMENT
16	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_INVESTMENT
17	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_INVESTMENT
18	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_INVESTMENT
19	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_INVESTMENT
20	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_INVESTMENT
21	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_POLICY
22	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_POLICY
23	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_POLICY
24	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_POLICY
25	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_POLICY
26	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_POLICY
27	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_POLICY
28	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_POLICY
29	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_POLICY
30	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_POLICY
31	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_PRODUCT
32	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_PRODUCT
33	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_PRODUCT
34	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_PRODUCT
35	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_PRODUCT
36	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_PRODUCT
37	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_PRODUCT
38	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_PRODUCT
39	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_PRODUCT
40	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_PRODUCT
41	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_CRIME
42	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_CRIME
43	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_CRIME
44	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_CRIME
45	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_CRIME
46	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_CRIME
47	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_CRIME
48	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_CRIME
49	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_CRIME
50	2025-04-04 04:43:52.618157+00	SHORT_ANSWER	FIN_CRIME
51	2025-04-04 04:43:52.618157+00	ESSAY	FIN_KNOWLEDGE
52	2025-04-04 04:43:52.618157+00	ESSAY	FIN_KNOWLEDGE
53	2025-04-04 04:43:52.618157+00	ESSAY	FIN_KNOWLEDGE
54	2025-04-04 04:43:52.618157+00	ESSAY	FIN_KNOWLEDGE
55	2025-04-04 04:43:52.618157+00	ESSAY	FIN_KNOWLEDGE
56	2025-04-04 04:43:52.618157+00	ESSAY	FIN_KNOWLEDGE
57	2025-04-04 04:43:52.618157+00	ESSAY	FIN_KNOWLEDGE
58	2025-04-04 04:43:52.618157+00	ESSAY	FIN_KNOWLEDGE
59	2025-04-04 04:43:52.618157+00	ESSAY	FIN_KNOWLEDGE
60	2025-04-04 04:43:52.618157+00	ESSAY	FIN_KNOWLEDGE
61	2025-04-04 04:43:52.618157+00	ESSAY	FIN_INVESTMENT
62	2025-04-04 04:43:52.618157+00	ESSAY	FIN_INVESTMENT
63	2025-04-04 04:43:52.618157+00	ESSAY	FIN_INVESTMENT
64	2025-04-04 04:43:52.618157+00	ESSAY	FIN_INVESTMENT
65	2025-04-04 04:43:52.618157+00	ESSAY	FIN_INVESTMENT
66	2025-04-04 04:43:52.618157+00	ESSAY	FIN_INVESTMENT
67	2025-04-04 04:43:52.618157+00	ESSAY	FIN_INVESTMENT
68	2025-04-04 04:43:52.618157+00	ESSAY	FIN_INVESTMENT
69	2025-04-04 04:43:52.618157+00	ESSAY	FIN_INVESTMENT
70	2025-04-04 04:43:52.618157+00	ESSAY	FIN_INVESTMENT
71	2025-04-04 04:43:52.618157+00	ESSAY	FIN_POLICY
72	2025-04-04 04:43:52.618157+00	ESSAY	FIN_POLICY
73	2025-04-04 04:43:52.618157+00	ESSAY	FIN_POLICY
74	2025-04-04 04:43:52.618157+00	ESSAY	FIN_POLICY
75	2025-04-04 04:43:52.618157+00	ESSAY	FIN_POLICY
76	2025-04-04 04:43:52.618157+00	ESSAY	FIN_POLICY
77	2025-04-04 04:43:52.618157+00	ESSAY	FIN_POLICY
78	2025-04-04 04:43:52.618157+00	ESSAY	FIN_POLICY
79	2025-04-04 04:43:52.618157+00	ESSAY	FIN_POLICY
80	2025-04-04 04:43:52.618157+00	ESSAY	FIN_POLICY
81	2025-04-04 04:43:52.618157+00	ESSAY	FIN_PRODUCT
82	2025-04-04 04:43:52.618157+00	ESSAY	FIN_PRODUCT
83	2025-04-04 04:43:52.618157+00	ESSAY	FIN_PRODUCT
84	2025-04-04 04:43:52.618157+00	ESSAY	FIN_PRODUCT
85	2025-04-04 04:43:52.618157+00	ESSAY	FIN_PRODUCT
86	2025-04-04 04:43:52.618157+00	ESSAY	FIN_PRODUCT
87	2025-04-04 04:43:52.618157+00	ESSAY	FIN_PRODUCT
88	2025-04-04 04:43:52.618157+00	ESSAY	FIN_PRODUCT
89	2025-04-04 04:43:52.618157+00	ESSAY	FIN_PRODUCT
90	2025-04-04 04:43:52.618157+00	ESSAY	FIN_PRODUCT
91	2025-04-04 04:43:52.618157+00	ESSAY	FIN_CRIME
92	2025-04-04 04:43:52.618157+00	ESSAY	FIN_CRIME
93	2025-04-04 04:43:52.618157+00	ESSAY	FIN_CRIME
94	2025-04-04 04:43:52.618157+00	ESSAY	FIN_CRIME
95	2025-04-04 04:43:52.618157+00	ESSAY	FIN_CRIME
96	2025-04-04 04:43:52.618157+00	ESSAY	FIN_CRIME
97	2025-04-04 04:43:52.618157+00	ESSAY	FIN_CRIME
98	2025-04-04 04:43:52.618157+00	ESSAY	FIN_CRIME
99	2025-04-04 04:43:52.618157+00	ESSAY	FIN_CRIME
100	2025-04-04 04:43:52.618157+00	ESSAY	FIN_CRIME
101	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_KNOWLEDGE
102	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_KNOWLEDGE
103	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_KNOWLEDGE
104	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_KNOWLEDGE
105	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_KNOWLEDGE
106	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_KNOWLEDGE
107	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_KNOWLEDGE
108	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_KNOWLEDGE
109	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_KNOWLEDGE
110	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_KNOWLEDGE
111	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_INVESTMENT
112	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_INVESTMENT
113	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_INVESTMENT
114	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_INVESTMENT
115	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_INVESTMENT
116	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_INVESTMENT
117	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_INVESTMENT
118	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_INVESTMENT
119	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_INVESTMENT
120	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_INVESTMENT
121	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_POLICY
122	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_POLICY
123	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_POLICY
124	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_POLICY
125	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_POLICY
126	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_POLICY
127	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_POLICY
128	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_POLICY
129	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_POLICY
130	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_POLICY
131	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_PRODUCT
132	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_PRODUCT
133	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_PRODUCT
134	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_PRODUCT
135	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_PRODUCT
136	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_PRODUCT
137	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_PRODUCT
138	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_PRODUCT
139	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_PRODUCT
140	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_PRODUCT
141	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_CRIME
142	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_CRIME
143	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_CRIME
144	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_CRIME
145	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_CRIME
146	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_CRIME
147	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_CRIME
148	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_CRIME
149	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_CRIME
150	2025-04-04 04:43:52.618157+00	MULTIPLE_CHOICE	FIN_CRIME
\.

--
-- Data for Name: quiz_option; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.quiz_option (is_correct, quiz_id, quiz_option_id, option_text) FROM stdin;
t	101	1	중앙은행은 화폐 발행과 통화정책을 담당한다.
f	119	73	단기 주가 변동만을 중시한다.
f	134	135	펀드에는 운용 수수료가 없다.
f	101	2	중앙은행은 일반 상업은행 업무를 본격적으로 수행한다.
f	101	3	중앙은행은 개인에게 직접 대출을 제공한다.
f	101	4	중앙은행은 세금 징수를 주 임무로 한다.
f	102	5	복리는 단순이자 계산 방식이다.
f	102	6	복리는 원금에 대해 정액 이자를 지급한다.
t	102	7	복리는 원금과 이전 이자를 합산하여 다시 이자를 계산한다.
f	102	8	복리는 전혀 이자가 붙지 않는 방식이다.
f	103	9	예금보험 보장 한도는 무제한이다.
f	103	10	예금보험제도는 보장 한도가 없다.
t	103	11	예금보험 보장 한도는 일정 금액(5천만 원)까지이다.
f	103	12	예금보험제도는 적립식 예금만 보장한다.
f	104	13	시중에 유동성이 증가한다.
f	104	14	대출이 쉬워진다.
f	104	15	대출금리가 하락한다.
t	104	16	시중 유동성이 줄어들 수 있다.
f	105	17	낮은 금리로 무조건 대출을 받을 수 있다.
f	105	18	별도의 담보 없이 대출이 가능하다.
t	105	19	대출 시 신용등급이 높으면 이자율이나 조건에서 유리하다.
f	105	20	신용등급이 높아도 대출 금리는 절대 바뀌지 않는다.
f	106	21	기획재정부
f	106	22	국회
t	106	23	중앙은행(한국은행)
f	106	24	법무부
f	107	25	담보의 가치가 높을수록 대출 승인은 어려워진다.
f	107	26	담보 가치가 높으면 대출금 상환 능력과 무관하다.
t	107	27	담보 가치가 높을수록 금융기관이 대출 회수 위험이 낮아진다.
f	107	28	담보는 금리 결정에 전혀 영향을 주지 않는다.
f	108	29	금융거래 국제 협약 체결
t	108	30	금융기관의 감독·검사 및 제재
f	108	31	세금 정책 수립
f	108	32	개인 투자자의 투자 전략 제공
f	109	33	대출금리가 상승한다.
f	109	34	기업의 투자 의욕이 감소한다.
f	109	35	시중자금이 은행으로 모인다.
t	109	36	소비와 투자 활동이 촉진될 가능성이 크다.
f	110	37	공개시장조작
f	110	38	지급준비율 조정
f	110	39	기준금리 조정
t	110	40	부가가치세 인상
t	111	41	증권회사 또는 은행에서 계좌를 개설한다.
f	111	42	중앙은행에서 직접 주식 계좌를 만든다.
f	111	43	기획재정부에 서류를 제출해야 한다.
f	111	44	금감원 홈페이지에서만 가능하다.
f	112	45	채권은 상환 의무가 없는 투자 상품이다.
t	112	46	채권은 발행 주체가 투자자에게 일정 이자를 지급한다.
f	112	47	채권은 주식과 동일하게 기업 지분을 의미한다.
f	112	48	채권은 만기가 없어 영구적으로 보유할 수 있다.
f	113	49	고수익을 기대하기 위함이다.
f	113	50	세금 혜택을 높이기 위함이다.
t	113	51	위험을 여러 자산에 분산시켜 줄이기 위함이다.
f	113	52	빠르게 큰 수익을 내기 위함이다.
f	114	53	주가가 떨어질수록 배당 수익률은 낮아진다.
f	114	54	배당 수익률이 높으면 반드시 주가 상승이 보장된다.
t	114	55	투자 원금 대비 배당금이 상대적으로 많다는 의미이다.
f	114	56	배당금을 재투자할 수 없다는 의미이다.
f	115	57	거래소에 상장되지 않는다.
t	115	58	특정 지수나 자산 가격을 추종하며, 주식처럼 매매 가능하다.
f	115	59	분산 투자가 불가능하다.
f	115	60	배당금이 전혀 없다.
f	116	61	PER이 높으면 항상 주가가 저평가되었다는 의미이다.
t	116	62	PER이 높으면 시장이 그 기업의 미래가치를 높게 평가한다는 의미일 수 있다.
f	116	63	PER은 배당 수익률의 다른 표현이다.
f	116	64	PER이 낮으면 투자가 불가능하다.
f	117	65	주가 하락 시 손실을 줄이는 목적이다.
f	117	66	주가 상승 시 레버리지 효과를 높이기 위한 목적이다.
t	117	67	주가 하락으로 인한 차익을 노리기 위한 목적이다.
f	117	68	배당금을 극대화하기 위한 목적이다.
f	118	69	기술적 분석은 기업의 재무제표만을 분석한다.
f	118	70	펀더멘털 분석은 차트 패턴만으로 투자 결정을 내린다.
f	118	71	두 분석 방법은 동일하게 매수 시점만 제시한다.
t	118	72	기술적 분석은 과거 시장 데이터를, 펀더멘털 분석은 기업 가치와 재무 상태를 평가한다.
t	119	74	기업의 내재 가치와 재무 상태를 가장 중요하게 본다.
f	119	75	경쟁사의 주가만을 주요 지표로 삼는다.
f	119	76	거시경제 지표와 무관하게 투자한다.
f	120	77	기업 경영에 적극 개입하여 주가 조작을 시도한다.
f	120	78	소액 주주만 참여할 수 있는 제도이다.
f	120	79	경영진과 이사회의 결정을 무조건적으로 지지한다.
t	120	80	경영진에게 주주 가치를 높이는 방향으로 경영을 요구하는 주주의 행동을 말한다.
t	121	81	정부 지출과 세율 조절로 경기를 안정화하려는 정책이다.
f	121	82	중앙은행이 금리를 조정하는 정책이다.
f	121	83	환율을 조절하는 무역 정책이다.
f	121	84	재정정책은 정부 지출 규모와 무관하다.
f	122	85	법인세 인상
f	122	86	정부의 인프라 투자 확대
t	122	87	기준금리 조정
f	122	88	공공근로 확대
f	123	89	부동산 가격 상승을 적극 장려하기 위함이다.
f	123	90	부동산 시장의 공급만 늘리기 위해서이다.
t	123	91	부동산 시장 과열 억제와 시장 안정을 위해서이다.
f	123	92	민간 건설회사의 수익 보장을 위해 도입되었다.
f	124	93	특정 소득층에만 지급되는 선별적 지원을 말한다.
t	124	94	정부가 모든 국민에게 조건 없이 일정 금액을 제공한다.
f	124	95	고소득층에게만 특별히 지급되는 제도이다.
f	124	96	근로 의무를 전제로 한 지원책이다.
f	125	97	세금 인하 시 경기가 필연적으로 침체된다.
t	125	98	조세정책은 거시경제 안정이나 소득 재분배에 영향을 준다.
f	125	99	세율 조절은 기업 활동에 전혀 영향을 주지 않는다.
f	125	100	조세정책은 국제 무역과 무관하다.
f	126	101	금리가 하락하여 투자 유입이 증가한다.
f	126	102	외국인 직접투자가 급증한다.
t	126	103	정부의 재정 운용 부담이 커지고 미래 세대에 채무 부담이 전가될 수 있다.
f	126	104	물가가 즉시 안정된다.
t	127	105	보편 복지는 모든 국민이 대상이고, 선별 복지는 특정 계층만을 대상으로 한다.
f	127	106	두 복지 형태는 사실상 차이가 없다.
f	127	107	선별 복지는 고소득층 대상 정책을 의미한다.
f	127	108	보편 복지는 소득이 낮은 사람에게만 적용된다.
f	128	109	물가가 심각하게 상승 중일 때
f	128	110	경기가 과열되어 부동산 가격이 급등할 때
t	128	111	경기가 침체되어 일자리 창출이 필요할 때
f	128	112	무역수지 흑자가 매우 클 때
f	129	113	개인이 운영하는 식당
t	129	114	고속도로, 국방, 치안 등과 같이 누구나 이용할 수 있는 재화나 서비스
f	129	115	유료 회원 전용 온라인 강의
f	129	116	민간 자본이 100% 출자한 철도
f	130	117	정부 지출을 늘려 재정을 확대한다.
f	130	118	세수보다 지출을 크게 하여 경제를 부양한다.
t	130	119	균형 재정을 유지하거나 채무 관리를 강화한다.
f	130	120	적자 국채 발행을 무제한으로 허용한다.
f	131	121	예금은 매달 일정 금액을 넣어야 하고, 적금은 자유롭게 목돈을 예치한다.
f	131	122	적금은 목돈을 한 번에 넣고, 예금은 매월 분할 납입한다.
t	131	123	예금은 목돈을 일시에 예치, 적금은 일정 기간 매월 납입한다.
f	131	124	예금은 적금보다 이자를 전혀 주지 않는다.
f	132	125	이익 창출보다 사회 봉사를 목적으로 한다.
t	132	126	미래에 발생할 수 있는 위험에 대비하는 것이 주목적이다.
f	132	127	보험은 이미 발생한 손실만 보장한다.
f	132	128	보험은 의무적으로 모든 국민이 가입해야 한다.
f	133	129	연금저축은 단기 투자 상품에 속한다.
t	133	130	세액공제 등 절세 혜택을 받을 수 있는 장기 금융상품이다.
f	133	131	연금은 만기가 되면 원금만 돌려받는다.
f	133	132	연금저축은 중도 해지가 전혀 불가능하다.
t	134	133	펀드는 주식이나 채권 등에 분산 투자할 수 있는 간접 투자 상품이다.
f	134	134	펀드는 반드시 한 종목에만 투자해야 한다.
f	134	136	펀드의 운용 결과는 항상 원금이 보장된다.
f	135	137	예금자 보호가 전혀 되지 않는다.
f	135	138	주식 투자만 가능하다.
t	135	139	수시 입출금이 가능하면서도 상대적으로 높은 이자를 기대할 수 있다.
f	135	140	CMA는 보험 상품의 일종이다.
f	136	141	ISA는 예·적금만 가입할 수 있다.
t	136	142	ISA는 금융상품을 한 계좌에 모아 세제 혜택을 받을 수 있는 상품이다.
f	136	143	ISA는 무조건 의무가입해야 하는 계좌이다.
f	136	144	ISA는 국내에서만 운영이 불가능하다.
f	137	145	적립식 펀드는 한 번에 거액을 투자해야 한다.
t	137	146	매월 일정 금액을 투자해 평균 매입 단가를 낮출 수 있다.
f	137	147	적립식 펀드는 환매가 불가능하다.
f	137	148	적립식 펀드는 분산투자가 전혀 불가능하다.
f	138	149	고정금리는 시장 금리에 따라 실시간 변동된다.
f	138	150	변동금리는 일정 기간 동안 금리가 고정된다.
t	138	151	고정금리는 약정 기간 동안 금리가 변하지 않고, 변동금리는 기준금리에 따라 변한다.
f	138	152	변동금리는 만기까지 이율이 바뀌지 않는다.
t	139	153	신용등급, 소득, 담보 가치 등이 종합적으로 고려된다.
f	139	154	오직 나이만으로 결정된다.
f	139	155	단순 추첨으로 결정된다.
f	139	156	금리가 낮으면 대출 한도도 자동으로 증가한다.
f	140	157	금리가 은행보다 항상 낮다.
f	140	158	대출 절차가 은행보다 엄격하다.
f	140	159	제2금융권의 대출은 대부분 정부 보증을 받는다.
t	140	160	은행 대비 대출이 비교적 쉬우나 금리가 높을 수 있다.
t	141	161	발신 번호가 은행 대표 번호처럼 보이더라도 돈을 요구할 수 있다.
f	141	162	항상 문자메시지를 통하지 않고 등기우편만 사용한다.
f	141	163	절대 개인정보나 계좌 비밀번호를 묻지 않는다.
f	141	164	공적 기관 사칭은 전혀 이루어지지 않는다.
f	142	165	스미싱은 전화 통화로만 개인정보를 빼내는 수법이다.
f	142	166	스미싱은 보이스피싱과 동일한 방식이다.
t	142	167	문자메시지 내 링크나 앱 설치를 유도하여 정보를 탈취하는 방식이다.
f	142	168	스미싱은 이메일 해킹 기술을 지칭한다.
f	143	169	대출 광고를 자세히 살펴보지 않고 무조건 저금리라고 믿는다.
t	143	170	합법 금융기관인지 여부와 금리 규정을 확인한다.
f	143	171	개인정보를 요구하면 모두 제공한다.
f	143	172	계약서 없이 구두 약속만으로 대출을 진행한다.
f	144	173	OTP나 보안카드를 타인에게 대신 맡긴다.
f	144	174	의심스러운 링크를 클릭해서 확인한다.
f	144	175	계좌나 카드정보를 SNS에 공유한다.
t	144	176	출처가 불명확한 메시지나 이메일 링크·파일은 열지 않는다.
f	145	177	상대방에게 더 자세한 정보를 요구한다.
t	145	178	은행 및 해당 기관에 연락하여 사실 여부를 확인하거나 지급정지를 요청한다.
f	145	179	일단 돈을 이체한 뒤 상황을 본다.
f	145	180	상대방에게 개인정보를 먼저 모두 알려준다.
f	146	181	공인인증서를 반드시 요구한다.
f	146	182	피해 금액을 곧바로 보상해준다.
t	146	183	전자금융사기는 금융 정보를 탈취하거나 자금을 편취하는 형태로 이루어진다.
f	146	184	항상 이메일을 통해서만 진행된다.
t	147	185	공식 URL과 동일한지, 보안 연결(https) 여부 등을 확인한다.
f	147	186	아무 사이트에서나 로그인해도 된다.
f	147	187	피싱 사이트는 도메인이 짧기 때문에 쉽게 구분된다.
f	147	188	피싱 사이트는 무조건 한글 도메인을 사용한다.
f	148	189	시간이 지난 후 경찰에 가면 늦기 때문에 아무 조치도 하지 않는다.
f	148	190	해당 금융기관에 문의하지 않는다.
t	148	191	즉시 금융기관에 신고하고 계좌 지급정지를 요청한다.
f	148	192	주변 지인들에게 말하지 않고 조용히 처리한다.
t	149	193	초기 투자자가 후속 투자자의 투자금으로 이익을 얻는 피라미드 구조이다.
f	149	194	다단계는 합법적인 판매 조직 형태이다.
f	149	195	투자금 없이도 무한정 수익이 보장된다.
f	149	196	제품 판매 없이도 네트워크 유지가 가능하다.
f	150	197	모든 인터넷 사이트 링크를 클릭해본다.
t	150	198	앱이나 프로그램 설치 시 출처를 확인한다.
f	150	199	공인인증서 비밀번호를 공유한다.
f	150	200	의심스러운 전화를 받으면 바로 개인정보를 제공한다.
\.


--
-- Data for Name: short_answer_quiz; Type: TABLE DATA; Schema: public; Owner: root
--

COPY public.short_answer_quiz (quiz_id, short_answer, short_first_hint, short_question, short_second_hint) FROM stdin;
1	금리	은행이 대출 시 적용하는 비용	돈의 사용에 대한 대가를 의미하는 한 단어는?	ㄱㄹ
2	복리	이자가 다시 원금에 포함되는 방식	이자가 계속 재투자되어 자산이 빠르게 증가하는 개념은?	ㅂㄹ
3	예금보험	은행이 파산해도 예금을 지켜주는 제도	금융사 파산 시 일정 금액까지 보호해주는 제도는?	ㅇㄱㅂㅎ
4	부담	이자 부담이 늘어나는 현상	이자율 상승 시 대출자의 무엇이 커지는가?	ㅂㄷ
5	금감원	금융 감독을 담당하는 기관	금융기관을 검사하고 소비자를 보호하는 기관은?	ㄱㄱㅇ
6	신용등급	대출 가능성을 평가하는 점수	채무 상환 능력을 수치화한 평가를 한 단어로 하면?	ㅅㅇㄷㄱ
7	지급준비율	은행의 최소 준비금 제도	은행이 예금의 일정 비율을 중앙은행에 예치하는 제도는?	ㅈㄱㅈㅂㅇ
8	통화정책	중앙은행이 통화량을 조절하는 정책	금리·통화량을 조절해 경제를 관리하는 정책은?	ㅌㅎㅈㅊ
9	담보	대출자가 빚을 갚지 않을 경우 제공하는 자산	채무 불이행 시 채권자에게 제공되는 자산이나 권리는?	ㄷㅂ
10	신용카드	선결제 후 상환 방식의 카드	외상 거래가 가능한 카드는?	ㅅㅇㅋㄷ
11	주식	기업의 소유권을 나타내는 증권	기업 지분을 사고파는 증권은?	ㅈㅅ
12	채권	정부나 기업이 돈을 빌릴 때 발행하는 증서	정부나 기업이 발행하고 일정 이자를 지급하는 증서는?	ㅊㄱ
13	분산투자	다양한 자산에 투자하여 리스크를 줄이는 방식	여러 자산에 투자해 위험을 줄이는 방법은?	ㅂㅅㅌㅈ
14	배당수익률	투자자가 받는 배당금의 수익률	주가 대비 배당금의 비율을 나타내는 지표는?	ㅂㄷㅅㅇㄹ
15	PER	기업의 주가가 수익에 비해 비싼지 판단하는 지표	주가가 주당순이익 대비 몇 배인지를 보여주는 지표는?	P E R
16	ETF	주가지수를 따라 움직이는 펀드	특정 지수를 추종하는 상장지수펀드는?	E T F
17	기술적분석	차트 분석을 활용하는 투자 기법	과거 가격 추이와 거래량으로 미래 가격을 예측하는 기법은?	ㄱㅅㅈㅂㅅ
18	펀더멘털분석	기업의 실적과 재무제표를 분석하는 투자법	기업의 재무 상태 등 내재 가치를 평가하는 기법은?	ㅍㄷㅁㄷㅂㅅ
19	공매도	주식을 빌려서 판 후 되사서 갚는 투자 기법	주가 하락 시 차익을 얻기 위해 주식을 빌려 파는 행위는?	ㄱㅁㄷ
20	가치투자	기업의 장기적 성장성을 보고 투자하는 방식	기업의 내재 가치를 중시하는 투자 방식은?	ㄱㅊㅌㅈ
21	재정정책	정부의 세금과 예산으로 경제를 조절하는 정책	정부가 지출과 세금으로 경제를 조정하는 방식은?	ㅈㅈㅈㅊ
22	통화정책	중앙은행이 돈의 양을 조절하는 정책	금리와 통화량을 조절하는 경제 정책은?	ㅌㅎㅈㅊ
23	부동산규제	부동산 시장의 급등을 막기 위한 조치	부동산 시장 과열을 방지하는 정책은?	ㅂㄷㅅㄱㅈ
24	기본소득	모든 국민에게 지급하는 최소한의 생활비	정부가 모든 국민에게 조건 없이 지급하는 소득은?	ㄱㅂㅅㄱ
25	재정건전성	정부가 재정을 안정적으로 운영하는 능력	국가 채무를 관리해 거시경제 안정을 도모하는 개념은?	ㅈㅈㄱㅈㅅ
26	조세정책	세금 정책을 통해 경제를 조절하는 방법	세율 조절로 경기에 영향을 주는 정책은?	ㅈㅅㅈㅊ
27	공공재	국가가 제공하는 필수 서비스	도로와 국방 등 개인 비용만으론 제공하기 어려운 재화는?	ㄱㄱㅈ
28	정부부채	국가가 빌린 돈	금리 인상, 미래 세대 부담 등의 문제가 발생하는 국가 빚은?	ㅈㅂㅂㅊ
29	보편복지	모든 국민이 받을 수 있는 사회적 지원	모든 국민을 대상으로 제공되는 복지는?	ㅂㅍㅂㅈ
30	확장적재정정책	경제 성장을 위해 정부가 돈을 더 쓰는 정책	경기 부양을 위해 정부 지출을 늘리는 재정 운용은?	ㅎㅈㅈㅈㅈㅊ
31	적금	매월 일정 금액 저축 후 만기에 수령	일정 기간 매달 일정 금액을 저축하고 만기에 원금+이자를 받는 상품은?	ㅈㄱ
32	예금	처음에 목돈을 예치 후 만기에 원리금 수령	목돈을 한 번에 입금 후 만기에 이자를 수령하는 상품은?	ㅇㄱ
33	보험	사고 등에 대비해 보장받을 수 있는 제도	위험 발생 시 재정적 손실을 보전해주는 금융 상품은?	ㅂㅎ
34	연금저축	노후 자금 마련을 위한 장기 금융 상품	은퇴 이후 소득을 대비해 일정 금액을 적립하는 장기 상품은?	ㅇㄱㅈㅊ
35	펀드	여러 종목에 분산 투자 가능	투자자들이 모은 돈을 전문 운용사가 투자하는 상품은?	ㅍㄷ
36	ISA	다양한 금융상품 운용 + 세제 혜택	여러 금융상품을 한 계좌에 담아 세제혜택을 받는 계좌는?	I S A
37	CMA	자금 운용 후 이자 지급	증권사에서 운용하며 수시 입출금이 가능하지만 금리가 상대적으로 높은 계좌는?	C M A
38	적립식펀드	분할 매수를 통해 위험 분산	매달 일정 금액으로 펀드에 분산 투자하는 방식은?	ㅈㄹㅅㅍㄷ
39	고정금리	계약 기간 동안 금리 불변	일정 기간 동안 금리가 변동 없이 고정되는 방식을?	ㄱㅈㄱㄹ
40	대출한도	대출 가능 범위를 정하는 기준	개인의 신용등급, 소득, 담보 가치 등을 종합해 결정되는 최대 대출액은?	ㄷㅊㅎㄷ
41	보이스피싱	출처 불명 전화, 개인정보 요구로 사기	전화나 메시지로 개인정보나 돈을 빼내는 사기를 무엇이라 하나?	ㅂㅇㅅㅍㅅ
42	스미싱	URL 클릭 유도 후 개인정보 탈취	문자메시지 악성 링크로 정보를 탈취하는 사기를 무엇이라 하나?	ㅅㅁㅅ
43	불법사금융	합법 금융기관인지 반드시 확인	비인가 금융기관이 고금리와 폭리 수수료를 취하는 불법 대출 행위를 무엇이라 하나?	ㅂㅂㅅㄱㅇ
44	사이버금융사기	계정 해킹, OTP탈취 등	인터넷 환경에서 보안장치를 무력화해 돈을 갈취하는 행위를 무엇이라 하나?	ㅅㅇㅂㄱㅇㅅㄱ
45	계좌이체사기	상대방 진위 먼저 확인 필요	급하게 돈을 요구해 진위를 파악하기 어렵게 만드는 사기를 무엇이라 하나?	ㄱㅈㅇㅊㅅㄱ
46	스팸이메일	수상한 링크 절대 클릭 금지	낯선 주소, 클릭 유도 링크 등이 포함된 이메일을 무엇이라 하나?	ㅅㅍㅇㅁㅇ
47	전자금융사기방지법	금융사기 예방 및 구제 절차	전자금융사기 예방과 피해보상을 규정한 법을 무엇이라 하나?	ㅈㅈㄱㅇㅅㄱㅂㅈㅂ
48	피싱사이트	공식 사이트 사칭	URL이 공식 사이트와 다르거나 보안 인증이 없는 위장 사이트를 무엇이라 하나?	ㅍㅅㅅㅇㅌ
49	지급정지	추가 피해 막기 위해 계좌 동결	금융 범죄 피해 후 즉시 금융기관에 요청해 계좌를 묶는 조치를 무엇이라 하나?	ㅈㄱㅈㅈ
50	다단계사기	후속 투자자의 투자금으로 앞선 투자자에게 배당	피라미드 구조로 후속 투자자 돈으로 수익금을 지급하는 사기를 무엇이라 하나?	ㄷㄷㄱㅅㄱ
\.